<a href="https://colab.research.google.com/github/vivsingh119/agentic-ai-practise/blob/master/3-encoding_nominal_onehotencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import pandas as pd;
from sklearn.preprocessing import OneHotEncoder

**Types of Categorical Data :**

**Nominal Categorical Data**
---
This is a type of categorical data
which is used to identify an object
uniquely without providing any additional information. We cannot rank them naturally.
Example:
     Names of Cities
     Name of a person.

**Ordinal Categorical Data**:
---
This is type of categorical data
which can be ranked naturally.
Example:
    Education Level, School Grades, Seniority Level
    Post Graduate School Graduate PhD
    
rank: PhD, Post Graduate, Graduate, School

In [44]:
df_township=pd.read_csv("https://raw.githubusercontent.com/vivsingh119/agentic-ai-practise/refs/heads/master/township.csv")
df_township

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [45]:
df_township.columns

Index(['town', 'area', 'price'], dtype='object')

In [46]:
df_township.dtypes

town     object
area      int64
price     int64
dtype: object

In [47]:
df_township['town'].unique()

array(['monroe township', 'west windsor', 'robinsville'], dtype=object)

In [48]:
df_township['town'].isna().sum()

np.int64(0)

In [49]:
ohe=OneHotEncoder()

In [50]:
ohe.fit(df_township[['town']])

OneHotEncoder()

In [51]:
ohe.transform(df_township[['town']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13 stored elements and shape (13, 3)>

In [52]:
encoded_df=ohe.transform(df_township[['town']]).toarray()
encoded_df

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [53]:
ohe.categories_

[array(['monroe township', 'robinsville', 'west windsor'], dtype=object)]

In [54]:
df_new=pd.DataFrame(encoded_df,columns=ohe.categories_,dtype=int)
df_new

   monroe township robinsville west windsor
0                1           0            0
1                1           0            0
2                1           0            0
3                1           0            0
4                1           0            0
5                0           0            1
6                0           0            1
7                0           0            1
8                0           0            1
9                0           1            0
10               0           1            0
11               0           1            0
12               0           1            0

In [55]:
pd.concat([df_township,df_new],axis=1)

,town,area,price,"(monroe township,)","(robinsville,)","(west windsor,)"
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,565000,1,0,0
2,monroe township,3200,610000,1,0,0
3,monroe township,3600,680000,1,0,0
4,monroe township,4000,725000,1,0,0
5,west windsor,2600,585000,0,0,1
6,west windsor,2800,615000,0,0,1
7,west windsor,3300,650000,0,0,1
8,west windsor,3600,710000,0,0,1
9,robinsville,2600,575000,0,1,0
10,robinsville,2900,600000,0,1,0
11,robinsville,3100,620000,0,1,0
12,robinsville,3600,695000,0,1,0

**Ordinal Encoder**

In [56]:
movie_df=pd.read_csv("https://raw.githubusercontent.com/vivsingh119/agentic-ai-practise/refs/heads/master/movie_review.csv")

In [57]:
movie_df

    age  gender education   review
0    30  Female    School  Average
1    68  Female        UG     Poor
2    70  Female        PG     Good
3    72  Female        PG     Good
4    16  Female        UG  Average
5    31  Female    School  Average
6    18    Male    School     Good
7    60  Female    School     Poor
8    65  Female        UG  Average
9    74    Male        UG     Good
10   98  Female        UG     Good
11   74    Male        UG     Good
12   51    Male    School     Poor
13   57  Female    School  Average
14   15    Male        PG     Poor
15   75    Male        UG     Poor
16   59    Male        UG     Poor
17   22  Female        UG     Poor
18   19    Male    School     Good
19   97    Male        PG     Poor
20   57  Female    School  Average
21   32    Male        PG  Average
22   18  Female        PG     Poor
23   96  Female    School     Good
24   16  Female        PG  Average
25   57  Female    School     Good
26   53  Female        PG     Poor
27   69  Female        PG     Poor
28   48    Male    School     Poor
29   83  Female        UG  Average
30   73    Male        UG  Average
31   22  Female    School     Poor
32   92    Male        UG  Average
33   89  Female        PG     Good
34   86    Male    School  Average
35   74    Male    School     Poor
36   34  Female        UG     Good
37   94    Male        PG  Average
38   45  Female    School     Good
39   76    Male        PG     Poor
40   39    Male    School     Good
41   23    Male        PG     Good
42   30  Female        PG     Good
43   27    Male        PG     Poor
44   77  Female        UG  Average
45   61    Male        PG     Poor
46   64  Female        PG     Poor
47   38  Female        PG     Good
48   39  Female        UG     Good
49   25  Female        UG     Good

In [58]:
movie_df.dtypes

age           int64
gender       object
education    object
review       object
dtype: object

In [59]:
movie_df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [60]:
movie_df['education'].isna().sum()

np.int64(0)

In [61]:
from sklearn.preprocessing import OrdinalEncoder

In [62]:
oe=OrdinalEncoder()
oe

OrdinalEncoder()

In [63]:
oe.fit(movie_df[['education']])

OrdinalEncoder()

In [64]:
oedf=oe.transform(movie_df[['education']])
oedf

array([[1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.]])

In [65]:
oe.categories_

[array(['PG', 'School', 'UG'], dtype=object)]

In [68]:
movie_df['education_encode_value']=oedf

In [69]:
movie_df

    age  gender education   review  education_encode_value
0    30  Female    School  Average                     1.0
1    68  Female        UG     Poor                     2.0
2    70  Female        PG     Good                     0.0
3    72  Female        PG     Good                     0.0
4    16  Female        UG  Average                     2.0
5    31  Female    School  Average                     1.0
6    18    Male    School     Good                     1.0
7    60  Female    School     Poor                     1.0
8    65  Female        UG  Average                     2.0
9    74    Male        UG     Good                     2.0
10   98  Female        UG     Good                     2.0
11   74    Male        UG     Good                     2.0
12   51    Male    School     Poor                     1.0
13   57  Female    School  Average                     1.0
14   15    Male        PG     Poor                     0.0
15   75    Male        UG     Poor                     2.0
16   59    Male        UG     Poor                     2.0
17   22  Female        UG     Poor                     2.0
18   19    Male    School     Good                     1.0
19   97    Male        PG     Poor                     0.0
20   57  Female    School  Average                     1.0
21   32    Male        PG  Average                     0.0
22   18  Female        PG     Poor                     0.0
23   96  Female    School     Good                     1.0
24   16  Female        PG  Average                     0.0
25   57  Female    School     Good                     1.0
26   53  Female        PG     Poor                     0.0
27   69  Female        PG     Poor                     0.0
28   48    Male    School     Poor                     1.0
29   83  Female        UG  Average                     2.0
30   73    Male        UG  Average                     2.0
31   22  Female    School     Poor                     1.0
32   92    Male        UG  Average                     2.0
33   89  Female        PG     Good                     0.0
34   86    Male    School  Average                     1.0
35   74    Male    School     Poor                     1.0
36   34  Female        UG     Good                     2.0
37   94    Male        PG  Average                     0.0
38   45  Female    School     Good                     1.0
39   76    Male        PG     Poor                     0.0
40   39    Male    School     Good                     1.0
41   23    Male        PG     Good                     0.0
42   30  Female        PG     Good                     0.0
43   27    Male        PG     Poor                     0.0
44   77  Female        UG  Average                     2.0
45   61    Male        PG     Poor                     0.0
46   64  Female        PG     Poor                     0.0
47   38  Female        PG     Good                     0.0
48   39  Female        UG     Good                     2.0
49   25  Female        UG     Good                     2.0

In [70]:
movie_df['education_encode_value']=movie_df['education_encode_value'].astype("int")

In [71]:
movie_df

    age  gender education   review  education_encode_value
0    30  Female    School  Average                       1
1    68  Female        UG     Poor                       2
2    70  Female        PG     Good                       0
3    72  Female        PG     Good                       0
4    16  Female        UG  Average                       2
5    31  Female    School  Average                       1
6    18    Male    School     Good                       1
7    60  Female    School     Poor                       1
8    65  Female        UG  Average                       2
9    74    Male        UG     Good                       2
10   98  Female        UG     Good                       2
11   74    Male        UG     Good                       2
12   51    Male    School     Poor                       1
13   57  Female    School  Average                       1
14   15    Male        PG     Poor                       0
15   75    Male        UG     Poor                       2
16   59    Male        UG     Poor                       2
17   22  Female        UG     Poor                       2
18   19    Male    School     Good                       1
19   97    Male        PG     Poor                       0
20   57  Female    School  Average                       1
21   32    Male        PG  Average                       0
22   18  Female        PG     Poor                       0
23   96  Female    School     Good                       1
24   16  Female        PG  Average                       0
25   57  Female    School     Good                       1
26   53  Female        PG     Poor                       0
27   69  Female        PG     Poor                       0
28   48    Male    School     Poor                       1
29   83  Female        UG  Average                       2
30   73    Male        UG  Average                       2
31   22  Female    School     Poor                       1
32   92    Male        UG  Average                       2
33   89  Female        PG     Good                       0
34   86    Male    School  Average                       1
35   74    Male    School     Poor                       1
36   34  Female        UG     Good                       2
37   94    Male        PG  Average                       0
38   45  Female    School     Good                       1
39   76    Male        PG     Poor                       0
40   39    Male    School     Good                       1
41   23    Male        PG     Good                       0
42   30  Female        PG     Good                       0
43   27    Male        PG     Poor                       0
44   77  Female        UG  Average                       2
45   61    Male        PG     Poor                       0
46   64  Female        PG     Poor                       0
47   38  Female        PG     Good                       0
48   39  Female        UG     Good                       2
49   25  Female        UG     Good                       2